a=int(input("Enter a First Number: "))
b=int(input("Enter b Second Number: "))
print("Addition: ",a+b)
print("Subtration: ",a-b)
print("Multipication: ",a*b)
print("Divide: ",a/b)
print("Reminder: ",a%b)
print("Exponent: ",a**b)
print("Floor: ",a//b)