# Generated by Django 3.0.7 on 2021-07-08 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_mgmt_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionYearModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('session_start_year', models.DateField()),
                ('session_end_year', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='students',
            name='session_end_year',
        ),
        migrations.RemoveField(
            model_name='students',
            name='session_start_year',
        ),
        migrations.AddField(
            model_name='attendance',
            name='session_year_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='student_mgmt_app.SessionYearModel'),
        ),
        migrations.AddField(
            model_name='students',
            name='session_year_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='student_mgmt_app.SessionYearModel'),
        ),
    ]
