# Generated by Django 3.1.7 on 2021-04-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_id', models.CharField(max_length=40)),
                ('Email', models.EmailField(max_length=15)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
    ]
