# Generated by Django 3.1.7 on 2021-04-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=40)),
                ('Email', models.EmailField(max_length=15)),
                ('Password', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Register',
        ),
    ]
