# Generated by Django 3.1.7 on 2021-04-03 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_system', '0003_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='Email',
        ),
        migrations.AddField(
            model_name='login',
            name='Password',
            field=models.CharField(default='', editable=False, max_length=50),
        ),
    ]
