# Generated by Django 3.2.4 on 2021-07-22 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0003_alter_stu_details_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stu_details',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
