# Generated by Django 3.2.4 on 2021-07-22 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0004_alter_stu_details_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stu_details',
            old_name='image',
            new_name='pic_image',
        ),
    ]
