# Generated by Django 3.2.4 on 2021-07-22 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0005_rename_image_stu_details_pic_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stu_details',
            name='pic_image',
        ),
    ]
