# Generated by Django 3.2.4 on 2021-07-22 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0006_remove_stu_details_pic_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='stu_details',
            name='pic_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
