# Generated by Django 3.2.4 on 2021-07-23 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0009_auto_20210723_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stu_details',
            name='address',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
