# Generated by Django 3.2.4 on 2021-07-23 03:29

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0010_alter_stu_details_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stu_details',
            name='phone_no',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
