# Generated by Django 3.2.4 on 2021-07-23 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0011_alter_stu_details_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stu_details',
            name='address',
            field=models.CharField(max_length=255),
        ),
    ]
