# Generated by Django 3.2.4 on 2021-07-25 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0014_auto_20210723_1624'),
    ]

    operations = [
        migrations.DeleteModel(
            name='image',
        ),
        migrations.AddField(
            model_name='stu_details',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
