# Generated by Django 3.2.4 on 2021-07-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0015_auto_20210725_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stu_details',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%D/'),
        ),
    ]
